# Auto-generated by fix_wave1_v5.py
# Consumed by verify.py to configure the sanitizer builds.

EXCLUDE = [
]

# -DOL_DISABLE_NUMA is a belt-and-suspenders flag; the header already
# checks __has_include(<numa.h>) but this makes the intent explicit.
EXTRA_FLAGS = [
    "-DOL_DISABLE_NUMA=1",
]
