#!/usr/bin/env python3
"""
OLSRT Wave 1 - build fix v4.

Comprehensive strategy:

  1. Identify all untracked .c files under src/code/streams/ (Qwen-generated
     variants). If the user passes --auto-exclude-untracked, add them all to
     the exclusion list in build_wave1_config.py.

  2. Update build_wave1_config.py to disable NUMA. Since ol_green_threads.h
     unconditionally defines OL_NUMA_AVAILABLE 1, we need to also patch that
     header to respect a disable flag.

  3. Report what we did.

Idempotent, safe to re-run.
"""

import argparse
import subprocess
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# NUMA header patch
# ---------------------------------------------------------------------------

NUMA_SEARCH = """    #if defined(__linux__)
        #include <sys/timerfd.h>
        #include <sys/eventfd.h>
        #include <linux/futex.h>
        #include <numa.h>
        #include <numaif.h>
        #define OL_NUMA_AVAILABLE 1"""

NUMA_REPLACE = """    #if defined(__linux__)
        #include <sys/timerfd.h>
        #include <sys/eventfd.h>
        #include <linux/futex.h>
        /* NUMA is optional: if libnuma-dev is not installed, the header
         * is still usable with OL_NUMA_AVAILABLE = 0. Defining
         * OL_DISABLE_NUMA (e.g. via -DOL_DISABLE_NUMA) forces the
         * no-NUMA code path even if <numa.h> is present. */
        #if !defined(OL_DISABLE_NUMA) && defined(__has_include)
            #if __has_include(<numa.h>)
                #include <numa.h>
                #include <numaif.h>
                #define OL_NUMA_AVAILABLE 1
            #else
                #define OL_NUMA_AVAILABLE 0
            #endif
        #elif !defined(OL_DISABLE_NUMA)
            #include <numa.h>
            #include <numaif.h>
            #define OL_NUMA_AVAILABLE 1
        #else
            #define OL_NUMA_AVAILABLE 0
        #endif"""

def patch_green_threads_header(root):
    target = root / "includes" / "code" / "streams" / "ol_green_threads.h"
    if not target.exists():
        print("[SKIP] ol_green_threads.h not found")
        return 0
    text = target.read_text(encoding="utf-8")
    if "OL_DISABLE_NUMA" in text:
        print("[SKIP] ol_green_threads.h: NUMA guard already present")
        return 0
    if NUMA_SEARCH not in text:
        print("[FAIL] ol_green_threads.h: NUMA anchor not found")
        print("       (The header might have been modified by Qwen. Manual review needed.)")
        return 1
    new = text.replace(NUMA_SEARCH, NUMA_REPLACE, 1)
    backup = target.with_suffix(target.suffix + ".orig")
    if not backup.exists():
        backup.write_text(text, encoding="utf-8")
    target.write_text(new, encoding="utf-8")
    print("[OK]   ol_green_threads.h: NUMA guard installed")
    return 0

# ---------------------------------------------------------------------------
# Untracked-file detection
# ---------------------------------------------------------------------------

def untracked_c_files(root):
    """Return a list of untracked .c files under src/code/streams/."""
    try:
        r = subprocess.run(
            ["git", "ls-files", "--others", "--exclude-standard",
             "src/code/streams/"],
            cwd=str(root), capture_output=True, text=True,
        )
        if r.returncode != 0:
            return []
        return [line.strip() for line in r.stdout.splitlines()
                if line.strip().endswith(".c")]
    except Exception:
        return []

# ---------------------------------------------------------------------------
# build_wave1_config.py generation
# ---------------------------------------------------------------------------

CONFIG_HEADER = """# Auto-generated by fix_wave1_v4.py
# Consumed by verify.py to configure the sanitizer builds.

# Files to exclude from the compilation (relative to OLSRT root).
# These are Qwen-generated variants that do not compile cleanly.
# The canonical implementations live in the non-suffixed files.
EXCLUDE = [
"""

CONFIG_FOOTER = """]

# Extra compile flags (prepended to the compiler command).
# -DOL_DISABLE_NUMA forces the no-NUMA path in ol_green_threads.h
# so that libnuma-dev is not required to build.
EXTRA_FLAGS = [
    "-DOL_DISABLE_NUMA=1",
]
"""

def write_build_config(root, exclude_list):
    target = root / "build_wave1_config.py"
    lines = [CONFIG_HEADER]
    for rel in exclude_list:
        lines.append('    "{}",\n'.format(rel))
    lines.append(CONFIG_FOOTER)
    target.write_text("".join(lines), encoding="utf-8")
    print("[OK]   wrote build_wave1_config.py  ({} exclude{})".format(
        len(exclude_list), "" if len(exclude_list) == 1 else "s"))

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def find_root(start):
    base = start.resolve()
    for c in [base] + list(base.parents)[:6]:
        if (c / "includes" / "olsrt.h").exists() and (c / "src").is_dir():
            return c
    return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", type=Path, default=None)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    root = args.root or find_root(Path.cwd())
    if root is None:
        print("ERROR: OLSRT root not found")
        return 1
    print("OLSRT root: " + str(root))
    print()

    # ---- 1. Detect untracked .c files ----
    print("Step 1: detect untracked .c files under src/code/streams/")
    print("-" * 60)
    untracked = untracked_c_files(root)
    if untracked:
        for f in untracked:
            print("  found: " + f)
    else:
        print("  (none)")

    # Always exclude the two known-bad files (from earlier diagnostics)
    hardcoded = [
        "src/code/streams/ol_actor_serialization.c",
        "src/code/streams/ol_actor_isolation.c",
    ]

    exclude_list = sorted(set(untracked) | set(hardcoded))

    print()
    print("Step 2: write build_wave1_config.py")
    print("-" * 60)
    print("  exclusion list ({}):".format(len(exclude_list)))
    for rel in exclude_list:
        print("    - " + rel)

    if not args.dry_run:
        write_build_config(root, exclude_list)
    else:
        print("[DRY] would write build_wave1_config.py")

    print()
    print("Step 3: patch ol_green_threads.h to make NUMA optional")
    print("-" * 60)
    fails = 0
    if not args.dry_run:
        fails += patch_green_threads_header(root)
    else:
        print("[DRY] would patch ol_green_threads.h")

    print()
    print("=" * 60)
    print("Failures: {}".format(fails))
    print()
    print("Next: run `python3 verify.py`")
    return 0 if fails == 0 else 2

if __name__ == "__main__":
    sys.exit(main())
